[package]
name = "orion_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
colored = "2.0"
clap = { version = "4.5.13"}
thiserror = "1.0"
env_logger = "0.11.5"

[lib]
name = "orion_cli"
path = "src/lib.rs"

[[bin]]
name = "orion_cli"
path = "src/main.rs"


